language: ruby

rvm:
  - 2.2.0

sudo: required

dist: trusty

services:
  - docker

install:
  - bundle install

script:
  - bundle exec rspec

after_success:
  - bundle exec codeclimate-test-reporter
